### PR TITLE
fix: Strip and ignore trailing hashes

### PR DESCRIPTION
**Pull request by Swatinem**
I have found that some symbols have a `$<32 hex digits>` suffix, that when stripped will demangle the symbol perfectly fine.

### CODE REVIEW

**Comment by khuey** [comment]
Do you have any idea where these come from? I've never seen this before.

**Comment by Swatinem** [comment]
Not entirely sure, this is one of the long list of demangling failures we get at sentry. It could be possible that they come from a different step of our pipeline and would need to be stripped out differently. CC @jan-auer ?

**Comment by khuey** [comment]
I'm not opposed to merging this but I would still like an answer to the question.

**Comment by Swatinem** [comment]
Hm, this slipped my radar. We were briefly looking into where these things might come from internally but didn’t find anything obvious looking through the code. I think we can deal with these suffixes in `symbolic` rather.

**Pull request closed without merging**
