### PR TITLE
Fix `no-default-features = true` for non-nightly rust channels

### PR DESCRIPTION
**Pull request by fitzgen**

### CODE REVIEW

**Comment by philipc** [comment]
> Fixed builds using `no-default-features = true` to not accidentally enable `no_std` mode, which requires nightly rust, and break builds on non-nightly channels

`no_std` is stable for libraries, so this should have been fine. We're doing this in other gimli-rs libraries too.

**Comment by fitzgen** [comment]
It is the use of `alloc` collections which are still unstable, and were feature'd on and enabled when the std feature was not present, thereby breaking anyone who had disabled default features (which I know are at least https://github.com/rustwasm/twiggy and https://github.com/alexcrichton/backtrace-rs).

**Comment by fitzgen** [comment]
One option would be to do a breaking change, the other is what is implemented here: `no-default-features` still uses std even though the `std` feature isn't enabled (I would change this if doing it all over from the start) and `alloc` is only used when the feature set is like `!std && alloc`. This technically breaks the "features may only be additive" rule, but since it involves nightly only things I don't think it matters much.

So downstream crates that disabled default features will still use std, because it is impossible for them to have enabled the alloc feature before it existed.

**Comment by fitzgen** [comment]
And now I see that this PR didn't implement what I jsut described in the last comment >.<

**Pull request merged**
